
if strcmpi(curr_block, 'test')
  send_xmlcmd_udp('fc-signal', 's:TODAY_DIR','', 's:VP_CODE','', 's:BASENAME','');
  wCL = 0;
else
  send_xmlcmd_udp('fc-signal', 's:TODAY_DIR',TODAY_DIR, 's:VP_CODE',VP_CODE, 's:BASENAME','lc_train');
  wCL = 1;
end
send_xmlcmd_udp('interaction-signal', 's:_feedback', 'LibetClock');
send_xmlcmd_udp('interaction-signal', 'command', 'sendinit');
general_port_fields.feedback_receiver= 'pyff';
send_xmlcmd_udp('interaction-signal', ...
  'i:writeClassifierLog', wCL, ...
  's:showClassifier', showClassifier, ...
  's:TODAY_DIR', TODAY_DIR, ...
  'cls_ival', cls_ival, ...  
  'i:nRev', 2, ...
  'i:trials', nTrials, ...
  'i:pauseAfter', 10, ...
  'i:revolutionTime', 4000, ...
  'cls_ival', cls_ival, ...
  'i:keypress_tolerance', keypress_tolerance);
send_xmlcmd_udp('interaction-signal', 'command', 'play');
disp('Type ''dbcont'' to quit the feedback and continue.')
keyboard
disp('Check if marker file .vhmrk was written correctly!')
send_xmlcmd_udp('interaction-signal', 'command', 'quit');
fprintf('Finshed.\n');
