  send_xmlcmd_udp('fc-signal', 's:TODAY_DIR',TODAY_DIR, 's:VP_CODE',VP_CODE, 's:BASENAME','lc_fb');
  send_xmlcmd_udp('interaction-signal', 's:_feedback', 'LibetClock');
  send_xmlcmd_udp('interaction-signal', 'command', 'sendinit');
  general_port_fields.feedback_receiver= 'pyff';
  send_xmlcmd_udp('interaction-signal', ...
    'i:writeClassifierLog', 1, ...
    's:showClassifier', 'feedback', ...
    's:TODAY_DIR', TODAY_DIR, ...
    'cls_ival', cls_ival, ...    
    'i:nRev', 2, ...
    'i:trials', nTrials, ...
    'i:pauseAfter', 10, ...
    'i:revolutionTime', 4000, ...
    'cls_ival', cls_ival, ...
    'i:keypress_tolerance', keypress_tolerance);
  send_xmlcmd_udp('interaction-signal', 'command', 'play');
  bbci_bet_apply(bbci.setup_file, 'bbci.feedback', bbci.feedback, 'bbci.fb_port', 12345);
  disp('type ''dbcont'' to quit the feedback and continue.')
  keyboard
  send_xmlcmd_udp('interaction-signal', 'command', 'quit');
  fprintf('Finshed.\n');