function opt= defopt_scalp_r_square(varargin);
% in construction

opt= propertylist2struct(varargin{:});
opt= set_defaults(opt, ...
                  'shading','flat', ...
                  'extrapolate',0, ...
                  'resolution', 61, ...
                  'colAx','0tomax', ...
                  'colorOrder',[0 0 0], ...
                  'colormap',cmap_hsv_fade(51, [4/6 0], 1, 1), ...
                  'contour',5, ...
                  'contour_policy','withinrange', ...
                  'contour_lineprop',{'LineWidth',0.3}, ...
                  'mark_properties',{'MarkerSize',6, 'LineWidth',1}, ...
                  'globalCLim',1);
