function opt= defopt_scalp_r2(varargin);
% in construction

opt= propertylist2struct(varargin{:});
opt= set_defaults(opt, ...
                  'shading','flat', ...
                  'extrapolate',1, ...
                  'extrapolateToMean',0, ...
                  'resolution', 71, ...
                  'colAx','sym', ...
                  'shrinkColorbar', 0.2, ...
                  'colorOrder',[0 0 0], ...
                  'colormap',cmap_posneg(51), ...
                  'lineWidth', 2, ...
                  'channelLineStyleOrder', {'thick','thin'}, ...
                  'ival_color', [0.8 0.8 0.8; 0.6 0.6 0.6], ...
                  'contour',5, ...
                  'contour_policy','withinrange', ...
                  'contour_lineprop',{'LineWidth',0.3}, ...
                  'mark_properties',{'MarkerSize',6, 'LineWidth',1}, ...
                  'channelAtBottom', 1, ...
                  'globalCLim',1, ...
                  'renderer', 'contourf', ...
                  'legend_pos','NorthWest');
