function opt= defopt_scalp_power2(varargin);
% in construction

opt= propertylist2struct(varargin{:});
opt= set_defaults(opt, ...
                  'shading','flat', ...
                  'extrapolate',1, ...
                  'extrapolateToMean', 0, ...
                  'resolution', 61, ...
                  'colAx','range', ...
                  'ival_color', [0.8 0.8 0.8; 0.6 0.6 0.6], ...
                  'lineWidth', 2, ...
                  'channelLineStyleOrder', {'thick','thin'}, ...
                  'renderer', 'contourf', ...
                  'colormap',cmap_hsv_fade(51, [4/6 0], 1, 1), ...
                  'contour',5, ...
                  'contour_policy','strict', ...
                  'contour_lineprop',{'LineWidth',0.3}, ...
                  'mark_properties',{'MarkerSize',6, 'LineWidth',1}, ...
                  'globalCLim',1, ...
                  'legend_pos','NorthEast');

