function opt= defopt_erps(varargin);
% in construction

opt= propertylist2struct(varargin{:});
opt= set_defaults(opt, ...
                  'lineWidth',0.7, ...
                  'axisType','cross', ...
                  'axisTitleVerticalAlignment', 'top', ...
                  'axisTitleFontWeight', 'demi', ...
                  'scaleHPos','left');
