function opt= defopt_scalp_csp(varargin);
% in construction

opt= propertylist2struct(varargin{:});
opt= set_defaults(opt, ...
                  'shading','flat', ...
                  'extrapolate',0, ...
                  'resolution', 61, ...
                  'linespec', {'LineWidth',2, 'Color','k'}, ...
                  'colAx','sym', ...
                  'colorOrder',[0 0 0], ...
                  'colormap',cmap_greenwhitelila(31), ...
                  'contour',5, ...
                  'contour_policy','withinrange', ...
                  'contour_lineprop',{'LineWidth',0.3}, ...
                  'mark_properties',{'MarkerSize',6, 'LineWidth',1}, ...
                  'globalCLim',1);
