function opt= defopt_spec(varargin);
% in construction

opt= propertylist2struct(varargin{:});
opt= set_defaults(opt, ...
                  'lineWidth',0.7, ...
                  'axisTitleVerticalAlignment', 'top', ...
                  'axisTitleFontWeight', 'demi', ...
                  'shrinkAxes', [0.95 0.9], ...
                  'scaleHPos','left', ...
                  'xTick', 10:10:1000, ...
                  'scalePolicy','auto');
