function [axesStyle, lineStyle]= opt_extractPlotStyles(opt)

style_list= {'box', 'visible', ...
             'tickLength', 'tickDir', 'tickDirMode', ...
             'xGrid', 'xTick', 'xTickLabel', ...
             'xTickMode', 'xTickLabelMode', ...
             'xLim', 'xScale', 'xAxisLocation', 'xColor', ...
             'yGrid', 'yTick', 'yTickLabel', 'yDir', ...
             'yTickMode', 'yTickLabelMode', ...
             'yLim', 'yScale', 'yAxisLocation', 'yColor', ...
             'colorOrder', 'lineStyleOrder', 'gridLineStyle', ...
             'fontAngle', 'fontName', 'fontSize', 'fontUnits', 'fontWeight'};
ai= 0;
axesStyle= {};
opt_fields= fieldnames(opt);
for is= 1:length(style_list),
  sm= strmatch(lower(style_list{is}), lower(opt_fields), 'exact');
  if length(sm)==1,
    ai= ai+2;
    axesStyle(ai-1:ai)= {style_list{is}, getfield(opt, opt_fields{sm})};
  end
end

line_style_list= {'lineWidth', 'lineStyle', ...
                  'marker', 'markerSize', 'markerEdgeColor', ...
                  'markerFaceColor'};
ai= 0;
lineStyle= {};
for is= 1:length(line_style_list),
  sm= strmatch(lower(line_style_list{is}), lower(opt_fields), 'exact');
  if length(sm)==1,
    ai= ai+2;
    lineStyle(ai-1:ai)= {line_style_list{is}, getfield(opt, opt_fields{sm})};
  end
end
