function mrk= mrkdefByClassDef(Mrk, file_type)

classDef_list= ...
    {'real_tactile', {1, 2; 'left tactile', 'right tactile'}, ...
     'imag_tactile', {1, 2; 'left tactile', 'right tactile'}, ...
     'real_visiual', {1, 2; 'left visual', 'right visual'}, ...
     'imag_visiual', {1, 2; 'left visual', 'right visual'}, ...
     'real_motor', {1, 2; 'left motor', 'right motor'}, ...
     'imag_motor', {1, 2; 'left motor', 'right motor'}};

mrk= NaN;
N= size(classDef_list, 1);
for n= 1:N,
  if strpatterncmp([classDef_list{n,1} '*'], file_type), 
    mrk= makeClassMarkers(Mrk, classDef_list{n,2}, 0,0);
    continue;
  end
end
