function mrk = mrkodef_HandWorkStation_Lab(mrko, varargin)

mrkDef = {'S 31', 'S 32', 'S 21', 'S 22', 'S 23', 'S 24', 'S 11', 'S 12', 'S 13', 'S 41', 'S 42', 'S255';
          'normal screw',...
          'fast screw',...
          'move barrel',...
          'tag barrel',...
          'untag one',...
          'untag all',...
          'correct catch',...
          'wrong catch',...
          'missed catch',...
          'start low',...
          'start high',...
          'end'};

mrk = mrk_defineClasses(mrko, mrkDef);
