function mrk = mrkodef_HandWorkStation_SMA(mrko, varargin)

mrkDef = {'S 10', 'S 11', 'S 20', 'S 21', 'S255';
          'start low',...
          'end low',...
          'start high',...
          'end high',...
          'end'};

mrk = mrk_defineClasses(mrko, mrkDef);
