function mrk= mrkodef_CNV(mrko, varargin)

stimDef= {11, 10;
          'go','cue'};
stimOffDef= {20, 21;
          'cue-off', 'go-off'};
miscDef= {240, 241, 248, 249, 254, 255;
          'countdown start', 'countdown end', ...
          'pause start', 'pause end', ...
          'run start', 'run end'};
mrk= mrkodef_general_oddball(mrko, 'stimDef',stimDef, ...
                             'respDef',[], ...           
                             'miscDef',miscDef);

mrk.stim_off= mrkodef_general_oddball(mrko, 'stimDef',stimOffDef, ...
                                      'respDef',[]);
