function mrk= mrkutil_addSpelledPhrase(mrk, letter_matrix)

mrk.spelledPhrase= {};
mrk.spelledSymbols= {};
for mm= 1:size(mrk.mode,1),
  idx= find(mrk.mode(mm,:));
  mrk_cls= mrk_chooseEvents(mrk.classified, find(mrk.classified.mode(mm,:)));
  
  switch(mrk.classified.modeName{mm}),
   case 'calibration',
    phrase= '';
    symb= '';
   case 'copyspelling',
    [mrk, phrase, symb]= ...
        mrkutil_assignLabelsToCopyspelling(mrk, mrk_cls, ...
                               'letter_matrix', letter_matrix, ...
                               'target_phrase', mrk.desiredPhrase{mm}, ...
                               'idx', idx);
    mrk.spelledPhrase{mm}= phrase;
    mrk.spelledSymbols{mm}= symb;
   case {'fixedspelling', 'freespelling'},
    [mrk_dmy, final_phrase, symb, final_up_to]= ...
        mrkutil_assignLabelsToOnlineSpelling(mrk, mrk_cls, ...
                              'letter_matrix', letter_matrix,...
                              'assign_labels', 0);
    mrk.spelledPhrase{mm}= final_phrase;
    mrk.spelledSymbols{mm}= symb;
    if ~isfield(mrk, 'desiredPhrase'),
      mrk.desiredPhrase{mm}= final_phrase;
    end
    [mrk, phrase, symb]= ...
        mrkutil_assignLabelsToOnlineSpelling(mrk, mrk_cls, ...
                               'letter_matrix', letter_matrix, ...
                               'target_phrase', mrk.desiredPhrase{mm}, ...
                               'final_phrase', final_phrase, ...
                               'idx', idx, ...
                               'final_up_to', final_up_to);
   otherwise
    error('unknown spelling mode');
  end
end
