%% does not work so far

setup_bbci_bet_unstable;

unix('xset s off');
unix('xset -dpms');

opt_fb= struct('client_machines',[]);
opt_fb.position= [1 410 800 600];
opt_fb.text_spec= {'FontName','Courier'};

opt_fb = set_defaults(opt_fb, ...
                      'status','pause',...
                      'bat_width',1/3,...
                      'bat_height',1/10,...
                      'ball_diameter',1/10,...
                      'speed',500,...
                      'ball_color',[0 0 1],...
                      'ball_hit_color',[0 1 0],...
                      'ball_miss_color',[1 0 0],...
                      'bat_color',[0.6,0.6,0.6],...
                      'ball_positions',2,...
                      'changed',0,...
                      'show_bit',0,...
                      'score',1,...
                      'damping',20,...
                      'countdown',5000,...
                      'fs',25,...
                      'reset',1,...
                      'sequence','Z',...
                      'relational',0,...
                      'parPort',1,...
                      'log',0,...
                      'position',[100 100 800 600],...
                      'background_color',[0.9,0.9,0.9],...
                      'matchpoints',100,...
                      'repetitions',1,...
                      'interbreak_interval',1000);

opt_movie= struct('freeze_out', 2);
opt_movie.fade_out= 1;
opt_movie.overwrite= 1;
opt= strukt('opt_fb',opt_fb, 'opt_movie',opt_movie);
opt.position= [1 410 800 600];
%opt.force_set= {{63, 'FontName','Courier', 'FontSize',0.05}};
opt.filename= 'brainpong_master';

global LOG_DIR
subdir= 'Michael_06_03_10';
LOG_DIR= [EEG_RAW_DIR subdir '/log/'];


logno= 5; % opt.start= 99; opt.stop= 338;
replay('brainpong', logno, opt, ...
       'save',sprintf('%s_brainpong_%03d', subdir, logno));

% replay('brainpong', logno, opt);
