function [opt]= setup_sound_presentation(varargin)
global VP_SCREEN VP_CODE BCI_DIR TODAY_DIR VLC_DIR SOUND_DIR STIM_DIR

opt= propertylist2struct(varargin{:});
opt
opt= set_defaults(opt, ...
                  'joystick',0, ...
                  'break',8, ...
                  'test', 0, ...
                  'require_response', 1, ...
                  'background', 0.5*[1 1 1], ...
                  'countdown', 7, ...
                  'countdown_fontsize', 0.3, ...
                  'duration_intro', 7000, ...
                  'bv_host', 'localhost', ...
                  'msg_intro','Entspannen', ...
                  'msg_fin', 'Ende', ...
                  'mssg',[], ...
                  'show_image',1, ...
                  'image_file', [BCI_DIR 'acquisition/data/images/kob.jpg']);
%opt= [];
opt.handle_background= stimutil_initFigure;
%opt.filename= 'muscog_artifacts';
if ~isempty(opt.mssg)
desc= stimutil_readDescription(opt.mssg);
h_desc= stimutil_showDescription(desc, 'waitfor',0);
opt.delete_obj= h_desc.axis;
end
%if opt.joystick
    opt.filename='sound_discretization'
%else
%    opt.filename='sound_discretization';
%end
fprintf('for testing:\n  sound_presentation(opt, ''test'',1);\n');
fprintf('for recording:\n  sound_presentation(opt);\n');

%fprintf('stim_oddballAuditory(N, opt);\n');
