pyff('init', 'PaintingFeedback');
pause(1);
data_path = 'c:\Dokumente und Einstellungen\ml\Eigene Dateien\stephan_luis\data\190412_145725\';
pyff('setint', 'n_groups', 4);
pyff('setint', 'group_size', 6);
pyff('set', 'prune', 0.03);
pyff('setint', 'n_objects', 15);
pyff('setint', 'debug', 0);
pyff('set', 'data_path', data_path);
pyff('setint', 'geometry', VP_SCREEN);
t = clock;
t_stamp = [num2str(t(4)) '_' num2str(t(5)) '.log'];
pyff('set', 'debug_path', [TODAY_DIR 'paint_' t_stamp]);