%% ERP validation
% initialization
session = {'session1', 'session2'};
dir = 'G:\DB\';
fs=100;
totalNUM=54;

%init
initParam = {'fs',100; ...
    'task',{'p300_off','p300_on'}; ...
    'channel_index', [1:32]; ...
    'band', [0.5 40]; ...
    'segTime', [-200 800]; ...
    'baseTime', [-200 0]; ...
    'selTime', [0 800]; ...
    'nFeature',10; ...
    'init_speller_length',1; ...
    'Nsequence', 5;...
    'one_seq_time', 2.75; ...
    'speller_text', {'A', 'B', 'C', 'D', 'E', 'F', ...
        'G', 'H', 'I', 'J', 'K', 'L', ...
        'M', 'N', 'O', 'P', 'Q', 'R', ...
        'S', 'T', 'U', 'V', 'W', 'X', ...
        'Y', 'Z', '1', '2', '3', '4', ...
        '5', '6', '7', '8', '9', '_'}; ...
    'spellerText_on', 'PATTERN_RECOGNITION_MACHINE_LEARNING'
};
%% validation
for sess = 1:length(session)
    for sub = 1:totalNUM
        fprintf('%d-th ...\n',sub);
        snum = num2str(sub);
        filetrain = fullfile([dir, session{sess},'\s',snum,'\EEG_P300.mat']);
        load(filetrain);
        CNT{1} = prep_resample(EEG_P300_train, fs,{'Nr', 0});
        CNT{2} = prep_resample(EEG_P300_test, fs,{'Nr', 0});
        [ACC.P300(sub,sess), ACC.P300_itr(sub,sess)] = erp_performance(CNT, initParam);
        fprintf('%d = %f\n',sub, ACC.P300(sub,sess));
        clear CNT EEG_P300_test EEG_P300_train filetrain Dat1 Dat2
    end
end

