
% All setups need to define a struct 'opt' with all required fields

opt.nPat = 3;
opt.usedPat = 'auto';
opt.nPat_csp = 3;
opt.usedPat_csp = 'auto';
opt.clab = {'not','E*','Fp*','AF*','OI*','I*','*9','*10'};
opt.ival = [];
opt.default_ival = [1250 3500];
opt.band = [];
opt.filtOrder = 5;
opt.ilen_apply = 750;
opt.visu_ival = [-500 5000];
opt.model = 'LSR';
opt.threshold = inf;
opt.editable = {'nPat','Number of CSPP patterns to use for each class';...
                'usedPat','Specified CSPP patterns to use';...
                'nPat_csp','Number of CSP patterns to use for each class';...
                'usedPat_csp','Specified CSP patterns to use';...
                'clab','Channels to use for patches';...
                'clab_csp','Channels to use for csp';...
                'ival','Time interval regarding stimulus to use';...
                'band','Frequency band to use';...
                'threshold','threshold to use for outlier removal'};
opt.nclassesrange = [2,2];
