
if ~exist('opt', 'var')
  opt = [];
end
opt = set_defaults(opt, 'leftright', 0, ... % if 1, compare left vs. right movement, else move vs. no move
                        'clab', bbci.clab, ...
                        'ival', [-1500 400], ...
                        'xTrials', [1 5], ...
                        'useAllChannels', 1, ...
                        'fractions', [1 1], ... % how much of the data is actually used (due to memory problems)                        
                        'winends_tr', -100:100:100, ...
                        'winends_te', -300:50:300, ... 
                        'idecay', 0, ... % decay of classifier output integration (0 = no integration)
                        ...
                        'erp_analysis', 1, ...
                        'erp_winsize', 1000, ...
                        'erp_baseline', 400, ...
                        'erp_nSamples', 5, ...
                        'erp_band', [1.5 3], ...
                        'erp_classWindow', 200, ...
                        'erp_classifier', 'RLDAshrink', ... %'{'libsvm', '-s 1 -c 10 -t 2'}'
                        'erp_gaussKernelConvolution', 0, ...
                        'erp_gaussStd', 1.5, ...
                        ...
                        'csp_analysis', 0, ...
                        'csp_nPat', 3, ...                        
                        'csp_winsize', 1000, ...
                        'csp_baseline', 400, ...
                        'csp_autoSelectBand', 0, ... % if 1, opt.csp_band is ignored
                        'csp_band', [15 25], ...
                        'csp_classWindow', 400, ...
                        'csp_classifier', 'RLDA');
                    