file_list_2s= {'Gabriel_00_09_05', ...
    'Gabriel_01_12_12', ...
    'Guido_02_01_08', ...
    'Pavel_01_11_23', ...
    'Roman_01_12_13', ...
    'Seppel_01_10_19', ...
    'Soeren_01_12_17', ...
    'Stefan_01_10_18', ...
    'Thorsten_02_01_15'};
file_list_1s= {'Gabriel_01_07_24', ...
    'Guido_02_01_08', ...
    'Pavel_01_11_23', ...
    'Roman_01_12_13', ...
    'Seppel_01_10_19', ...
    'Soeren_01_12_17', ...
    'Stefan_01_10_18', ...
    'Thorsten_02_01_15'};
file_list_0_5s= {'Gabriel_01_07_24', ...
    'Gabriel_01_12_12', ...
    'Guido_02_01_08', ...
    'Pavel_01_11_23', ...
    'Roman_01_12_13', ...
    'Seppel_01_10_19', ...
    'Soeren_01_12_17', ...
    'Stefan_01_10_18', ...
    'Thorsten_02_01_15'};

tcl= -120;

lrp.clab= {'F#','FFC#','FC#','CFC','C#','T7,8','CCP#','CP#','TP7,8','PCP#',...
          'P#','PPO#'};
lrp.ilen= 1270;
lrp.fft_params= {[0.8 3], 128, 100};
lrp.jmeans= 10;

model_LPM= struct('classy','LPM', 'msDepth',2, 'std_factor',2);
model_LPM.param= struct('index',2, 'scale','log', ...
                        'value', [-2:2:5]);

model= model_LPM;

%% 'outer_ms'=1 means slightly cheating.
%% use 'outer_ms'=0 for a sound validation, but that requires 
opt_xv= struct('verbosity',2, 'out_trainloss',1 ,...
               'outer_ms',1, 'progress_bar',0);

tap_list= {'2s', '1s', '0_5s'};

for tt= 1:length(tap_list),
  file_list= eval(['file_list_' tap_list{tt}]);

  for ff= 1:length(file_list),
    file= file_list{ff};
    is= min(find(file=='_'));
    subject= file(1:is-1);
    full_name= [file '/selfpaced' tap_list{tt} subject];
    [cnt, mrk, mnt]= loadProcessedEEG(full_name);
    valid= find(any(mrk.y==1,1));
    mrk= mrk_selectEvents(mrk, valid);
    [equi.idcs, pace]= getEventPairs(mrk, 8000);
    cnt= proc_selectChannels(cnt, lrp.clab);
    epo = makeEpochs(cnt, mrk, [-lrp.ilen 0]+tcl);
    fv = proc_filtBruteFFT(epo, lrp.fft_params{:});
    fv = proc_jumpingMeans(fv, lrp.jmeans);
    
    [ll, ls, out]= xvalidation(fv, model, opt_xv, ...
        'sample_fcn',{'divisionsEqui',[10 10],equi}, ...
        'ms_sample_fcn',{'divisions',[3 10 -1]}, ...
        'out_prefix', ['lrp' tap_list{tt} '_' file ': ']);
    loss(ff,tt)= ll(1);
    loss_std(ff,tt)= ls(1);
    loss_train(ff,tt)= ll(2);
    fprintf('\n');
  end
end
