bbci= strukt('fs', 1000, ...
             'save_name', [EEG_RAW_DIR 'null1/null_classifier'], ...
             'player', 1, ...
             'host', 'brainamp', ...
             'log', 0, ...
             'ringBufferSize', 30000, ...
             'maxDataLength', 40000, ...
             'maxBufLength', 100, ...
             'minDataLength', 10, ...
             'mrkQueueLength', 100);

opt = [];
analyze = [];
cls = struct('fv',1, ...
             'C',[], ...
             'applyFcn', inline('0', 'C','x'));
feature = strukt('cnt',1, ...
                 'ilen_apply', 10);
cont_proc = strukt('clab',{'*'});
post_proc = [];
marker_output = [];

save_setup;
