opt= [];
opt.handle_background= stimutil_initFigure;

h= [];
h.ax= axes('Position', [0.1 0.1 0.8 0.8]);
set(h.ax, 'Color',[0 0 0], 'XTick',[], 'YTick',[]);

h.im_dev= stimutil_readimages('koffer_einzelobjekte/dev_obj_*');
h.im_std= stimutil_readimages('koffer_einzelobjekte/std_obj_*');

desc= stimutil_readDescription('visual_oddball_v01');
h_desc= stimutil_showDescription(desc, 'waitfor',0);

opt= set_defaults(opt, ...
            'perc_dev',0.15, ...
            'isi',1500 , ...
            'require_response',1, ...
            'cue_dev', h.im_dev, ...
            'cue_std', h.im_std, ...
            'test', 0, ...
            'delete_obj', h_desc.axis);

fprintf('To start experiment type:\n  stim_oddballVisual(200, opt);');
