fv= proc_selectIval(epo, [500 1500]);
fv.proc=['fv= proc_csp(epo, 1); ' ...
         'fv= proc_variance(fv); ' ...
         'fv= proc_logNormalize(fv); '];

fv= proc_selectIval(epo, [500 2000]);
fv.proc=['fv= proc_csp(epo, 1); ' ...
         'fv= proc_variance(fv); ' ...
         'fv= proc_logNormalize(fv); '];

fv= proc_selectIval(epo, [500 2250]);
fv.proc=['fv= proc_csp(epo, 1); ' ...
         'fv= proc_variance(fv); ' ...
         'fv= proc_logNormalize(fv); '];

fv= proc_selectIval(epo, [1000 1500]);
fv.proc=['fv= proc_csp(epo, 1); ' ...
         'fv= proc_variance(fv); ' ...
         'fv= proc_logNormalize(fv); '];

fv= proc_selectIval(epo, [1000 2000]);
fv.proc=['fv= proc_csp(epo, 1); ' ...
         'fv= proc_variance(fv); ' ...
         'fv= proc_logNormalize(fv); '];

fv= proc_selectIval(epo, [1000 2250]);
fv.proc=['fv= proc_csp(epo, 1); ' ...
         'fv= proc_variance(fv); ' ...
         'fv= proc_logNormalize(fv); '];

fv= proc_selectIval(epo, [500 1500]);
fv.proc=['fv= proc_csp(epo, 2); ' ...
         'fv= proc_variance(fv); ' ...
         'fv= proc_logNormalize(fv); '];

fv= proc_selectIval(epo, [500 2000]);
fv.proc=['fv= proc_csp(epo, 2); ' ...
         'fv= proc_variance(fv); ' ...
         'fv= proc_logNormalize(fv); '];

fv= proc_selectIval(epo, [500 2250]);
fv.proc=['fv= proc_csp(epo, 2); ' ...
         'fv= proc_variance(fv); ' ...
         'fv= proc_logNormalize(fv); '];

fv= proc_selectIval(epo, [1000 1500]);
fv.proc=['fv= proc_csp(epo, 2); ' ...
         'fv= proc_variance(fv); ' ...
         'fv= proc_logNormalize(fv); '];

fv= proc_selectIval(epo, [1000 2000]);
fv.proc=['fv= proc_csp(epo, 2); ' ...
         'fv= proc_variance(fv); ' ...
         'fv= proc_logNormalize(fv); '];

fv= proc_selectIval(epo, [1000 2250]);
fv.proc=['fv= proc_csp(epo, 2); ' ...
         'fv= proc_variance(fv); ' ...
         'fv= proc_logNormalize(fv); '];

fv= proc_selectIval(epo, [500 1500]);
fv.proc=['fv= proc_csp(epo, 3); ' ...
         'fv= proc_variance(fv); ' ...
         'fv= proc_logNormalize(fv); '];

fv= proc_selectIval(epo, [500 2000]);
fv.proc=['fv= proc_csp(epo, 3); ' ...
         'fv= proc_variance(fv); ' ...
         'fv= proc_logNormalize(fv); '];

fv= proc_selectIval(epo, [500 2250]);
fv.proc=['fv= proc_csp(epo, 3); ' ...
         'fv= proc_variance(fv); ' ...
         'fv= proc_logNormalize(fv); '];

fv= proc_selectIval(epo, [1000 1500]);
fv.proc=['fv= proc_csp(epo, 3); ' ...
         'fv= proc_variance(fv); ' ...
         'fv= proc_logNormalize(fv); '];

fv= proc_selectIval(epo, [1000 2000]);
fv.proc=['fv= proc_csp(epo, 3); ' ...
         'fv= proc_variance(fv); ' ...
         'fv= proc_logNormalize(fv); '];

fv= proc_selectIval(epo, [1000 2250]);
fv.proc=['fv= proc_csp(epo, 3); ' ...
         'fv= proc_variance(fv); ' ...
         'fv= proc_logNormalize(fv); '];
