function [hax, restore_spec]= stimutil_initFigure(varargin)
%STIMUTIL_INITFIGURE - Initialize Matlab Figure for Cue Presentation
%
%Synopsis:
% [H_AX, RESTORE_SPEC]= stimutil_initFigure('Prop1', VALUE1, ...)
%
%Optional Properties:
% 'position': Position of the figure.
% 'backgorund': Background color of the figure.
%
%Returns:
% H_AX: Handle of axis
% RESTORE_SPEC: Use set(gcf, RESTORE_SPEC{:}) to restore original figure.

% blanker@cs.tu-berlin.de, Nov-2007

global VP_SCREEN

opt= propertylist2struct(varargin{:});
opt= set_defaults(opt, ...
                  'position', VP_SCREEN, ...
                  'background', 0.5*[1 1 1], ...
                  'hide_pointer', 0);
%                  'position', get(0, 'Screensize'), ...

hfig= gcf;
restore_spec= {'Position', get(hfig, 'Position'), ...
               'Units', get(hfig, 'Units'), ...
               'Pointer', get(hfig, 'Pointer'), ...
               'PointerShapeCData', get(hfig, 'PointerShapeCData')};

if opt.hide_pointer,
  set(hfig, 'Pointer', 'custom', ...
            'PointerShapeCData', repmat(NaN, 16, 16));
end

set(hfig, 'Color', opt.background, ...
          'Units', 'pixel', ...
          'Position', opt.position, ...
          'DefaultAxesPosition', [0 0 1 1], ...
          'DoubleBuffer', 'on', ...
          'Interruptible','off', ...
          'Clipping','off', ...
          'HitTest','off', ...
          'MenuBar', 'none', ...
          'NumberTitle', 'off');
clf;
figure(hfig);     %% Try to get it to the foreground
hax= axes;
set(hax, 'Visible', 'off', ...
         'Clipping', 'off', ...
         'HitTest', 'off', ...
         'Interruptible', 'off', ...
         'DrawMode','fast', ...
         'XLim', [-1 1], ...
         'YLim', [-1 1]);
axis('equal');
set(hax, 'XLimMode', 'manual', ...
         'YLimMode', 'manual');
