% Different runscripts that can be accessed through the GUI
global VP_SCREEN;
clear exp_opt;
clear exp_res;

% volume = [0.05 0.036 0.043 0.047 0.054 0.05];   

if ~exist('simulate_run', 'var'),
    simulate_run = 0;
end

switch do_action,
    case 'give_available_experiments',
        available_experiments = {'Rest EEG (eyes open)', 'Rest EEG (eyes closed)', 'Show sounds', 'Oddball fast', 'Oddball slow', 'Run block'};
        requires_online = [0 0 0 0 0 0];
        feedback_type = 'matlab';
        available_parameters = {{'impedances', 0, 'duration', 3}, ...
            {'impedances', 0, 'duration', 3}, ...
            {}, ...
            {'impedances', 0, 'nrStimuli', 150, 'perc_dev', .17, 'isi', 200}, ...
            {'impedances', 0, 'nrStimuli', 180, 'perc_dev', .2, 'isi', 1000}, ...
            {'impedances', 0, 'isi', 200, 'maxRounds', 10, 'requireResponse', 1, 'nrExtraStimuli', 3}, ...           
            };
        
    case available_experiments{1}, %EEG ruhe eyes open
        clear exp_opt glo_opt;
        glo_opt = struct();
        exp_opt = set_defaults(glo_opt, gui_set_opts);        
        exp_opt = set_defaults(exp_opt, ...
            'filename', 'RestEyesOpen', ...
            'duration', 3, ...
            'impendances', 0);

        bvr_startrecording(exp_opt.filename, ...
            'impedances', exp_opt.impedances);
        
        pause(exp_opt.duration*60);
        
        bvr_sendcommand('stoprecording');
        
    case available_experiments{2}, %EEG ruhe eyes closed
        clear exp_opt glo_opt;
        glo_opt = struct();
        exp_opt = set_defaults(glo_opt, gui_set_opts);        
        exp_opt = set_defaults(exp_opt, ...
            'filename', 'RestEyesClosed', ...
            'duration', 3, ...
            'impendances', 0);

        bvr_startrecording(exp_opt.filename, ...
            'impedances', exp_opt.impedances);
        
        pause(exp_opt.duration*60);
        
        bvr_sendcommand('stoprecording');        
        
    case 'Oddball fast'
        clear exp_opt glo_opt;
%         glo_opt.calibrated = diag(volume);
        glo_opt.toneDuration = 40;
        glo_opt.speakerSelected = [6 2 4 1 5 3];
        glo_opt.language = 'german';        
        setup_spatialbci_GLOBALgui;
        figure(99);

        exp_opt = set_defaults(glo_opt, gui_set_opts);
        exp_opt = set_defaults(exp_opt, ...
            'nrStimuli', 200, ...
            'perc_dev', 20/100, ...
            'alternative_placing', 1, ...
            'require_response', 0, ...
            'bv_host', 'localhost', ...
            'isi', 200, ...
            'filename', 'oddballStandard200Messung', ...
            'speech_intro', '', ...
            'fixation', 1, ...
            'vp_screen', [-1920 0 1920 1200], ...
            'msg_fin', 'End', ...
            'msg_intro', 'Entspannen', ...
            'speech_dir', 'C:\svn\bbci\acquisition\data\sound\german\upSampled', ...
            'fs', 44100, ...
            'speaker_number', 6, ...
            'countdown', 0, ...
            'impendances', 0, ...
            'use_speaker', 1, ...
            'cue_std', stimutil_generateTone(500, 'harmonics', 7, 'duration', 50, 'pan', 1, 'fs', 44100, 'rampon', 10, 'rampoff', 10), ...
            'cue_dev', stimutil_generateTone(1000, 'harmonics', 7, 'duration', 50, 'pan', 1, 'fs', 44100, 'rampon', 10, 'rampoff', 10));
        
        exp_opt.cue_dev = exp_opt.cue_dev * exp_opt.calibrated(exp_opt.use_speaker, exp_opt.use_speaker);
        exp_opt.cue_std = exp_opt.cue_std * exp_opt.calibrated(exp_opt.use_speaker, exp_opt.use_speaker);
        
        VP_SCREEN = exp_opt.vp_screen;
        
        if simulate_run,
            exp_opt.bv_host = '';
            exp_opt.filename = '';
            exp_opt.test = 1;          
        end
        stim_oddballAuditory(exp_opt.nrStimuli, exp_opt);

    case 'Oddball slow'
        clear exp_opt glo_opt;
%         glo_opt.calibrated = diag(volume);
        glo_opt.toneDuration = 40;
        glo_opt.speakerSelected = [6 2 4 1 5 3];
        glo_opt.language = 'german';        
        setup_spatialbci_GLOBALgui;
        figure(99);

        exp_opt = set_defaults(glo_opt, gui_set_opts);
        exp_opt = set_defaults(exp_opt, ...
            'nrStimuli', 200, ...
            'perc_dev', 20/100, ...
            'alternative_placing', 1, ...
            'require_response', 0, ...
            'bv_host', 'localhost', ...
            'isi', 1000, ...
            'filename', 'oddballStandard1000Messung', ...
            'speech_intro', '', ...
            'fixation', 1, ...
            'vp_screen', [-1920 0 1920 1200], ...
            'msg_fin', 'End', ...
            'msg_intro', 'Entspannen', ...
            'speech_dir', 'C:\svn\bbci\acquisition\data\sound\german\upSampled', ...
            'fs', 44100, ...
            'speaker_number', 6, ...
            'countdown', 0, ...
            'impendances', 0, ...
            'use_speaker', 1, ...            
            'cue_std', stimutil_generateTone(500, 'harmonics', 7, 'duration', 50, 'pan', 1, 'fs', 44100, 'rampon', 10, 'rampoff', 10), ...
            'cue_dev', stimutil_generateTone(1000, 'harmonics', 7, 'duration', 50, 'pan', 1, 'fs', 44100, 'rampon', 10, 'rampoff', 10));
        
        exp_opt.cue_dev = exp_opt.cue_dev * exp_opt.calibrated(exp_opt.use_speaker, exp_opt.use_speaker);
        exp_opt.cue_std = exp_opt.cue_std * exp_opt.calibrated(exp_opt.use_speaker, exp_opt.use_speaker);
        
        VP_SCREEN = exp_opt.vp_screen;
        
        if simulate_run,
            exp_opt.bv_host = '';
            exp_opt.filename = '';
            exp_opt.test = 1;          
        end
        stim_oddballAuditory(exp_opt.nrStimuli, exp_opt);

    case 'Show sounds'
        clear exp_opt glo_opt;
%         glo_opt.calibrated = diag(volume);
        glo_opt.toneDuration = 40;
        glo_opt.speakerSelected = [6 2 4 1 5 3];
        glo_opt.language = 'german';
        setup_spatialbci_GLOBALgui;
%         glo_opt.volume = volume';
        
        util_speakerCalibration(glo_opt);
        
        
    otherwise,
        % global options, set for each run
        clear exp_opt glo_opt;
%         glo_opt.calibrated = diag(volume);
        glo_opt.toneDuration = 40;
        glo_opt.speakerSelected = [6 2 4 1 5 3];
        glo_opt.language = 'german';
        glo_opt.longToneDuration = 600;
        setup_spatialbci_GLOBALgui;
        setup_spatialbci_FIXED_sequence;
        
        exp_opt = set_defaults(glo_opt, gui_set_opts);
        exp_opt = set_defaults(exp_opt, ...
            'isi', 175, ...
            'isi_jitter', 0, ...
            'countdown', 0, ...
            'repeatTarget', 3, ...
            'text_nrCounted', 'Wie vielen haben Sie gezählt?', ...
            'vp_screen', [-1920 0 1920 1200], ...
            'maxRounds', 10, ...
            'appPhase', 'train', ...
            'trial_pause', 1, ...
            'startup_pause', 3, ...
            'post_target_pause', .5, ...
            'repeatShortTarget', 2, ...
            'repeatLongTarget', 1, ...
            'pre_target_pause', .5, ...
            'post_trial_pause', 1, ...
            'end_tone_freq', 110, ...
            'end_tone_duration', 1000, ...
            'impendances', 0);

        VP_SCREEN = exp_opt.vp_screen;

        switch do_action,
            case 'Run block', 
                if isfield(exp_opt, 'spellString'),
                    exp_opt = rmfield(exp_opt, 'spellString');
                end
                exp_opt = set_defaults(exp_opt, ...
                    'filename', 'OnlineTrainFile', ...
                    'itType', 'fixed', ...
                    'mode', 'copy', ...
                    'application', 'FIXED_sequence', ...
                    'nrRounds', 1, ...
                    'requireResponse', 1, ...
                    'useSpeech', 0, ...
                    'nrExtraStimuli', 3, ...
                    'responseOffset', 100, ...
                    'sayLabels', 0, ...
                    'sayResult', 0, ...
                    'nrConditions', 2, ...
                    'randomTrial', round(rand), ...
                    'targetSeq', heikosequencer);                              
        end
        
        if simulate_run,
            exp_opt.bv_host = '';
            exp_opt.filename = '';
            exp_opt.test = 1;
            exp_opt.doLog = 0;
            exp_opt.randomClass=1;
            exp_opt.appPhase = 'train';            
        end
        
        exp_opt.impedanceCheck = exp_opt.impedances;
        
        %start the actual stuff
        exp_res = auditory_MainRoutine(exp_opt);
end
