%bbci.train_file='VPeac_10_01_25/imag_fbarrow_pmeanVPeac'
bbci.train_file='VPeac_10_01_25/imag_fbarrow_pcovmeanVPeac'
%bbci.train_file='VPeac_10_01_25/real_movementVPeac'
bbci.classDef = {1,2;'left','right'};
bbci.player = 1;
bbci.setup = 'cspauto';
%bbci.save_name = 'VPeac_10_01_25/imag_fbarrow_pmeanVPeac';
bbci.save_name = 'VPeac_10_01_25/imag_fbarrow_pcovmeanVPeac';
%bbci.save_name = 'VPeac_10_01_25/real_movementVPeac';
bbci.feedback = '1d';
bbci.classes = {'left','right'};
bbci.setup_opts.reject_artifacts=0;
bbci.withgraphics=0;