EEG_AUGCOG_DIR= ['/home/neuro/data/AUGCOG/'];

augcog_file= 'augcog_exp_database.txt';

[file, season, carf, audio, visual, calc,comb]= ...
    textread(augcog_file, '%s%f%s%s%s%s%s', 'delimiter',',');
file= deblank(file);
carf = deblank(carf);
audio = deblank(audio);
visual = deblank(visual);
calc = deblank(calc);
comb = deblank(comb);
season = num2cell(season);

augcog= struct('file', file, ...
               'season',season,...
               'carf', carf,...
	       'audio', audio,...
	       'visual',visual,...
	       'calc',calc,...
               'comb',comb);

