addpath([BCI_DIR 'import/m2html']);

cd(BCI_DIR);
list= {'acquisition','toolbox','online'};

for ii= 1:length(list),
  subfolder= list{ii};
  m2html('mfiles', subfolder, ...
         'htmldir', [DATA_DIR 'doc/' subfolder '/'], ...
         'recursive', 'on', ...
         'template', 'frame');
  cmd= sprintf('scp -r %s fiesta.cs.tu-berlin.de:/home/ml/ml/www/bbci/doc/', ...
             [DATA_DIR 'doc/' subfolder]);
  unix_cmd(cmd, 'could not copy to web folder');
end

cd([fileparts(BCI_DIR(1:end-1))]);
subfolder= 'ml';
m2html('mfiles', subfolder, ...
       'htmldir', [DATA_DIR 'doc/' subfolder '/'], ...
       'recursive', 'on', ...
       'index','menu');
cmd= sprintf('scp -r %s fiesta.cs.tu-berlin.de:/home/ml/ml/www/bbci/doc/', ...
             [DATA_DIR 'doc/' subfolder]);
unix_cmd(cmd, 'could not copy to web folder');
