function webify_feedbackScore(fid, score_list)

fprintf(fid, '<table>\n');
for ie= 1:length(score_list),
  if ie==1,
    col_tag= ' bgColor=#FF0000';
  elseif ie<=3,
    col_tag= ' bgColor=#DD9900';
  else
    col_tag= ' bgColor=#CCCCCC';
  end
  fprintf(fid, ['<tr> <td%s align="right">&nbsp;%d.&nbsp;</td> ' ...
                '<td%s>&nbsp;%s&nbsp;</td> ' ...
                '<td%s align="right">&nbsp;%.1f&nbsp;</td> ' ...
                '<td%s>&nbsp;%s&nbsp;</td> ', ...
                '<td%s>&nbsp;%s&nbsp;</td> </tr>\n'], ...
          col_tag, ie, ...
          col_tag, score_list(ie).subject, ...
          col_tag, score_list(ie).score, ...
          col_tag, score_list(ie).date, ...
          col_tag, score_list(ie).log_file);
end
fprintf(fid, '</table>\n');
