function postproc_bipolar(subdir, varargin)

global DATA_DIR EEG_RAW_DIR EEG_MAT_DIR

if nargin==0 | isempty(subdir) | isequal(subdir,'today'),
  dd= dir(EEG_RAW_DIR);
  subdir_list= {dd.name};
  today_str= datestr(now, 'yy/mm/dd');
  today_str(find(today_str==filesep))= '_';
  iToday= strpatternmatch(['*' today_str], subdir_list);
  subdir= subdir_list(iToday);
end
if subdir(1)~='/',
  subdir= [EEG_RAW_DIR subdir];
end
while subdir(end)=='/',
  subdir(end)= [];
end
subpath= subdir;
[dmy,subdir]= fileparts(subpath);

opt= propertylist2struct(varargin{:});
opt= set_defaults(opt, ...
                  'tmpdir', [DATA_DIR '/bbciRaw_tmp/' subdir], ...
                  'monodir', [DATA_DIR '/bbciRaw_mono/' subdir]);


cmd= sprintf('rm -f %s/*eog_mono*', subpath);
unix_cmd(cmd, 'could not remove eog_mono files');
cmd= sprintf('rm -f %s/*emg_mono*', subpath);
unix_cmd(cmd, 'could not remove emg_mono files');

%% look which files need to be processed
dd= dir([subpath '/*.eeg']);
%% delete postfix '.eeg'
file_list= apply_cellwise({dd.name}, inline('x(1:end-4)','x'));
%% some files should be skipped
%% (impedance measurements are in raw format anyway, and
%% eog_mono are generated by this script)
idx= strpatternmatch('impedances*', file_list);
file_list(idx)= [];

ff= 0;
while ff<length(file_list),
  ff= ff+1;
  file= file_list{ff};
  isdig= ismember(file, '0123456789');
  is= max(find(~isdig));
  file_list{ff}= [file(1:is) '*'];
  append_files= setdiff(strpatternmatch(file_list{ff}, file_list), ff);
  file_list(append_files)= [];
end

if ~exist(opt.tmpdir, 'dir'),
  mkdir(opt.tmpdir);
end
if ~exist(opt.monodir, 'dir'),
  mkdir(opt.monodir);
end

fprintf('processing files from directory %s\n', subpath);
for ff= 1:length(file_list),
  file= file_list{ff};
  fprintf('processing %s\n', file);

  %% load signals and markers
  [cnt, mrk]= eegfile_loadBV([subpath '/' file], 'prec',1);
  cnt.title= [subdir '/' file];

  cmd= sprintf('mv %s/%s.* %s', subpath, file, opt.tmpdir);
  unix_cmd(cmd, 'could not move original files to tmp dir');

  %% get the original monopolar EOG channels
  eog= proc_selectChannels(cnt, 'EOG*');
  %% and save them in a separate file
  eegfile_writeBV(eog, mrk, 'filename',[opt.monodir subdir '_eog_mono']);
  %% get the original monopolar EOG channels
  eog= proc_selectChannels(cnt, 'EMG*');
  %% and save them in a separate file
  eegfile_writeBV(eog, mrk, 'filename',[opt.monodir subdir '_emg_mono']);

  %% calculate bipolar EOG and EMG channels and save the data
  cnt= intproc_bipolarEOGEMG(cnt);
  eegfile_writeBV(cnt, mrk, 'filename',[subpath '/' file]);
end
